第4回課題提出
k-matsumoto-0221/RaiseTech-kadai-retake pull request #4
Opened 2024-05-03 02:35 UTC by k-matsumoto-0221

第4回目の課題が完了いたしました。
お手数ですが、ご確認をお願いいたします。

2024-05-10 15:11 UTC, MasatoshiMizumoto requested changes
コメント入れましたのでご対応お願いします！！

2024-05-10 15:11 UTC, MasatoshiMizumoto commented on lecture04/img/drawio/EnvConfDiagram.png
Regionの色が違うかもしれないので一度確認ください！

2024-05-11 00:57 UTC, k-matsumoto-0221 commented
ご確認いただきありがとうございます。
Regionの色合いをデフォルト値(RGB(0, 164, 166))に修正してみました。
Webで他の構成図とも比較してみましたが、だいぶ近い色になったかと思います。

2024-05-11 01:03 UTC, MasatoshiMizumoto commented
> ご確認いただきありがとうございます。 Regionの色合いをデフォルト値(RGB(0, 164, 166))に修正してみました。 Webで他の構成図とも比較してみましたが、だいぶ近い色になったかと思います。

色を変えたということでしょうか？
正しい色の図形が選べるはずなので、色の変更での対応はナシとさせてください！
（もし色認識について不得意な色があるという話であれば探すのも難しいと思いますので、このままでいいです！）

2024-05-11 14:36 UTC, k-matsumoto-0221 commented
前回の修正は図形を選択後、RGB値を編集するといった修正を行いました。
そして、今回コミットした内容は図形の置換を行なっております。(区別が付くか分かりませんが… 。)
一つ上のコミットは誤りですので、無視でお願いします。

図形の編集を行う上で、こちらのリンクを参考にさせていただきました。
- [参考リンク1](https://aws.amazon.com/jp/architecture/icons/)
- [参考リンク2](https://techblog.forgevision.com/entry/2020/12/05/100500)

2024-05-11 15:08 UTC, MasatoshiMizumoto approved these changes
LGTMです！！

2024-05-11 15:14 UTC, merged