第5回課題提出
k-matsumoto-0221/RaiseTech-kadai-retake pull request #5
Opened 2024-05-13 13:35 UTC by k-matsumoto-0221

第5回目の課題が完了いたしました。
お手数ですが、ご確認をお願いいたします。

2024-05-14 01:15 UTC, MasatoshiMizumoto reviewed
いくつかコメント入れましたのでご対応お願いします！！

2024-05-14 01:15 UTC, MasatoshiMizumoto commented on lecture05/lecture05.md
> +    - <font color="Red">サンプルは第 3 回で案内済みのものを使用すること</font>
このスタイルが反映されていないので、外すか他のスタイルでお願いします！！

2024-05-14 01:15 UTC, MasatoshiMizumoto commented on lecture05/lecture05.md
> +  - ![環境構成図](./env/drawio/EnvConfDiagram.png)
InternetとALBのアイコンが古いように見えますので他と合わせてください！
「アイコンのコンセプトが違うかも？」と感じたらそれは不適切なアイコンだと理解してもらって差し支えないです！

2024-05-14 01:15 UTC, MasatoshiMizumoto commented on lecture05/lecture05.md
> +  - 構築を行なった手順は [こちら](./work/step04/step04.md) に記載
手順やログを格納しておくのはGOODです！
一方で私（レビュアー）は結果だけ先に見たいという話になるので、
であればココに結果部分のスクショも追加してもらうのが良いかなと思います！！
（結果を見てもらう→経過に疑問があればログも見られるようにしておく、という流れ）

2024-05-14 09:43 UTC, k-matsumoto-0221 commented
ご確認ありがとうございます。
上記3点について、修正させていただきましたので、ご確認をお願いできればと思います。
(1点目については他ファイルにも確認できましたので、合わせて修正しております。)

2024-05-14 10:25 UTC, k-matsumoto-0221 commented
ご確認ありがとうございます。
上記3点について、修正させていただきましたので、ご確認をお願いできればと思います。
**Revert**したコミットは無視でお願いします。

2024-05-14 13:02 UTC, MasatoshiMizumoto commented on lecture05/lecture05.md
> +![環境構成図](./env/drawio/EnvConfDiagram.png)
- ロードバランサーの名前とアイコンが異なる
- Internetのアイコンが異なる（異なるアイコンパックから引用している）

2024-05-14 13:03 UTC, MasatoshiMizumoto requested changes
構成図がまだ気になるのでご対応お願いします！

2024-05-14 15:36 UTC, k-matsumoto-0221 commented
構成図について、以下の修正を行いましたので、ご確認をお願いいたします。
- internet
  - 以下のライブラリから画像を使用しました
    - AWS18/General Resources
- ALB
  - **Application Load Balancer** と表示があったものを使用しました

2024-05-15 03:54 UTC, MasatoshiMizumoto approved these changes
LGTMです！！
お疲れさまでした！

2024-05-15 09:46 UTC, merged